---
- name: Build and deploy Docker container
  hosts: localhost
  become: true
  tasks:
    - name: Build Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        build: .
        path: "{{ dockerfile_path }}"
    
    - name: Push Docker image to Docker Hub
      docker_image:
        name: "{{ dockerhub_username }}/{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        push: true
        source: build
        load: true

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ dockerhub_username }}/{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        restart_policy: always
