---
- name: Docker Image and Container Management
  hosts: localhost
  become: true
  vars:
    image_name: "finalproject2xyz"
    container_name: "finalproject2xyzcontainer"
    dockerfile_path: "./Dockerfile"

  tasks:
    - name: Build Docker Image from Dockerfile
      docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ image_name }}"
        tag: "latest"

    - name: Create and start Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:latest"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"  # Exposing port for web applications
