---
- name: Build Docker Image and Run Container
  hosts: localhost
  become: true

  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        build: "/var/lib/jenkins/workspace/xyzcicdpipeline-ansibledocker"
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        state: present

    - name: Ensure Docker container is running
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  # Example port mapping
      environment:
        DOCKER_HOST: unix:///var/run/docker.sock
